# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Ansa
email: davidansa00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you'll find my Cloud Resume Challenge. I have successfully 
  used HTML and CSS to create a website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidansa.com" # the base hostname & protocol for your site
twitter_username: ansaldn
github_username:  da5905p

# Build settings
markdown: kramdown

theme: jekyll-theme-slate